### ISSUE TITLE
unicode-whitespace-setup(t) fails with "Character invalid or undisplayable: Space" on emacs 25

### ISSUE THREAD

**Issue by berhoel** [rolandwalker/unicode-whitespace#3]
I am running 

GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-08-11 on KAEL

and am trying to get unicode whitespace to work. It fails with 

"Character invalid or undisplayable: Space"

on (unicode-whitespace-setup t)

**Comment by rolandwalker** [comment]
Hi!  Thanks!

So far, I was not able to duplicate in a clean VM with 25.0.50.1 2015-08-11 or HEAD on OS X, installing via `list-packages` from MELPA-stable.

Perhaps you are running an older version of `ucs-utils.el`, upon which this library depends?  The package definition lists `ucs-utils.el` version 0.7.6 as a dependency, but `ucs-utils.el` is actually now at version 0.8.4.

Maybe 25.0.50.1 needs ucs-utils 0.8.4.

**Comment by berhoel** [comment]
Loading "ucs-utils.el" via helm-locate-library opens

;; Version: 0.8.4
;; Last-Updated: 26 Aug 2015

list-packages lists
  ucs-utils          20150826.714  dependency

which seems to be the from melpa

**Comment by rolandwalker** [comment]
OK, you are using MELPA and not MELPA-stable.  I'll try that.  You should also try quitting Emacs and then deleting the relevant cache file by

``` bash
$ rm ~/.emacs.d/var/pcache/ucs-utils
```

But it must be done while Emacs is not running.

**Comment by berhoel** [comment]
Great, thank you. Deleting the cache has solved my problem.
